scraper.interval-ms=10000
camel.opentelemetry.enabled=false
otel.service.name=gig-hub
otel.exporter.otlp.endpoint=http://localhost:4318
otel.exporter.otlp.protocol=http/protobuf
otel.traces.exporter=logging
otel.logs.exporter=none
otel.metrics.exporter=none
camel.springboot.main-run-controller=true
fetchers.banquet.url=https://www.banquetrecords.com/events?w=1000
# fetchers.ticketmaster.api-key=your_ticketmaster_api_key
# fetchers.ticketmaster.venues.royalalberthall.id=KovZpZAEdntA
# slack.webhook-url=https://hooks.slack.com/services/your/webhook/url
# slack.channel=#events
# redis.url=rediss://default:<password>@<host>:6379
