spring.application.version=@project.version@
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
management.info.env.enabled=true
info.app.version=@project.version@
runner.interval-ms=10000
camel.opentelemetry.enabled=false
otel.service.name=gig-hub
otel.exporter.otlp.endpoint=http://localhost:4318
otel.exporter.otlp.protocol=http/protobuf
otel.traces.exporter=logging
otel.logs.exporter=none
otel.metrics.exporter=none
camel.springboot.main-run-controller=true
fetchers.banquet.url=https://www.banquetrecords.com/events?w=1000
fetchers.ticketmaster.venues.royal-albert-hall.id=KovZ9177Arf
fetchers.ticketmaster.venues.brixton-academy.id=KovZ91777af
fetchers.ticketmaster.venues.eventim-apollo.id=KovZpZAtadaA
fetchers.ticketmaster.venues.royal-festival-hall.id=KovZpZAnFvlA
# slack.webhook-url=https://hooks.slack.com/services/your/webhook/url
# slack.channel=#events
# redis.url=rediss://default:<password>@<host>:6379
gig-hub-calendar.base-url=${GIGHUBCALENDAR_BASEURL:}
