scrapers.banquet.url=https://www.banquetrecords.com/events?w=1000
scrapers.royal-albert-hall.url=https://www.royalalberthall.com/tickets/events/
# slack.webhook-url=https://hooks.slack.com/services/your/webhook/url
# slack.channel=#events
# redis.url=rediss://default:<password>@<host>:6379
# ticketmaster.api-key=your_ticketmaster_api_key
# ticketmaster.venue-id=KovZpZAEdntA